#!/usr/bin/env bash

# Analyze every UI file with the metadata generated by the current Qt build.
# Relative module imports require a complete, isolated copy of the UI tree.
punchi_lint_built_qml() (
    set -euo pipefail
    local project_root="$1"
    local build_dir="$2"
    local lint_bin="$3"
    local lint_log="$4"
    local lint_root
    lint_root="$(mktemp -d "$build_dir/qmllint-ui.XXXXXXXX")"
    trap 'rm -rf -- "$lint_root"' EXIT
    trap 'exit 130' INT
    trap 'exit 143' TERM

    cp -a "$project_root/contents/ui" "$lint_root/ui"
    cp -a "$project_root/contents/code" "$lint_root/code"
    local module_file
    for module_file in qmldir punchidockintegration.qmltypes; do
        cp -- "$build_dir/bin/org/punchi/dock/$module_file" \
            "$lint_root/ui/org/punchi/dock/$module_file"
    done

    local -a qml_files=()
    mapfile -d '' qml_files < <(find "$lint_root/ui" -name '*.qml' -print0 | sort -z)
    local lint_status=0
    "$lint_bin" "${qml_files[@]}" >"$lint_log" 2>&1 || lint_status=$?
    # Keep diagnostics tied to source files after the temporary tree is removed.
    LINT_SOURCE_PREFIX="$project_root/contents/ui" LINT_COPY_PREFIX="$lint_root/ui" \
        python3 - "$lint_log" <<'PY'
import os
import pathlib
import sys

log = pathlib.Path(sys.argv[1])
log.write_text(log.read_text().replace(
    os.environ["LINT_COPY_PREFIX"], os.environ["LINT_SOURCE_PREFIX"]))
PY
    exit "$lint_status"
)
